# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20170817_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='count',
        ),
    ]
