# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-18 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_remove_course_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
